export const ACTION_UPDATE_NAME = 'ACTION_UPDATE_NAME';
export const ACTION_UPDATE_GENERAL_INFO = 'ACTION_UPDATE_GENERAL_INFO';
export const ACTION_UPDATE_CV_URL = 'ACTION_UPDATE_CV_URL';
export const ACTION_UPDATE_USER_INFO = 'ACTION_UPDATE_USER_INFO';
export const ACTION_UPDATE_AGE = 'ACTION_UPDATE_AGE';
export const ACTION_UPDATE_ABILITIES = 'ACTION_UPDATE_ABILITIES';
export const ACTION_UPDATE_PORTFOLIO = 'ACTION_UPDATE_PORTFOLIO';
export const ACTION_UPDATE_PORTFOLIO_PROJECT = 'ACTION_UPDATE_PORTFOLIO_PROJECT';