import "@/app/css/globals.css";
import Sidebar from "@/components/sidebar";
import classNames from "classnames";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(inter.className, 'text-slate-700')}>
        <div className={classNames('w-full')}>
          <Sidebar />
          <div className={classNames('lg:pl-[300px]', 'w-full', 'h-auto', 'float-left')}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
